### ISSUE TITLE
How to get this running?

### ISSUE THREAD

**Issue by ruze00** [Cognation/darwin#7]
I followed the directions, and the server is running at http://0.0.0.0:8080.  The UI is running at http://localhost:3000.

When I try to create a new project from scratch, it shows that it's trying to POST to http://localhost:3000/undefined/create_project
with a 404.

What's the config setting to get this to work?

**Comment by ruze00** [comment]
Ok seemed like my .env wasn't being picked up.

`export REACT_APP_BACKEND = "http://localhost:8080"`

fixed it.

**Comment by 9throok** [comment]
Hey @ruze00 thanks for trying Darwin out. Hope the installation was easy. The dockers for running the frontend and the backend will be soon released easing out the installation.
